### ISSUE TITLE
Unassigned owner after user deletion

### ISSUE THREAD

**Issue by KaterinaBzatkova** [CZERTAINLY/CZERTAINLY-Core#703]
**Describe the bug**
Suppose a user is assigned to some certificate as an owner.  When the user is deleted, the user remains as the certificate owner. 
 
**To Reproduce**

Assign some user to a certificate
Delete the user
Go to the certificate detail
See the assigned owner

**Expected behavior**
The expected behavior is that the user deletion should be reflected in the certificate owner attribute - "Unassigned".

**Comment by lubomirw** [comment]
Fixed by implementing handling owner association separately
