### ISSUE TITLE
Improper certificate filter negation

### ISSUE THREAD

**Issue by doloban** [CZERTAINLY/CZERTAINLY-Core#813]
Certificate filtering with negation doesnt work properly.

The bug is specifically tied to filter condition not equals while filtering custom attributes. In our environment we have attribute "Purpose" for certificates, which is multi select list. Sum of our certificates is 500 and 90 of them have this attribute assigned with specific value (for the sake of explanation let's say "A").  A filter condition, where custom attribute "Purpose" equals to that specific value "A" shows 90 certificates, so one would expect to opposite condition, not equals, to show the opposite, 410 certificates, or atleast different number, but it shows 475 certificates, so I don't see the logic behind it.

Further examples or explanation can be provided from our side if needed.

**Comment by lubomirw** [comment]
Issue will be resolved together with CZERTAINLY/CZERTAINLY-Core#741 as a part of filters refactoring
