### ISSUE TITLE
Cannot make HTTPS WinRM connection in CZERTAINLY

### ISSUE THREAD

**Issue by doloban** [CZERTAINLY/CZERTAINLY-Core#865]
Hello,
we have trouble with establishing HTTPS connection. HTTP works fine, but in production environment we would like to use more secure HTTPS connection. Everything should be configured correctly: the CA that issued the TLS certificate is trusted by CZERTAINLY, the TLS certificate is correctly set on both HTTPS listener and Service. Network Service has access to the private key of the TLS certificate. Went through all of the steps mentioned here https://docs.czertainly.com/docs/certificate-key/integration-guides/adcs/winrm-configuration/. CZERTAINLY version is 2.11. Sending logs.
[winrmhttpserror.log](https://github.com/user-attachments/files/17255475/winrmhttpserror.log)

**Comment by 3keyroman** [comment]
Hello @doloban , I see there is an error:
```
Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
```

Do you have correct configuration of trusted certificates? What version of PyADCS connector you are using?
